### ISSUE TITLE
Current master HEAD version does not work

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-perceval-mozilla#25]
Current master HEAD, when installed in a virtual envirionment with master HEAD for perceval, has the following behavior:

```
>>> import perceval.backends.mozilla.crates
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/gl-perceval/lib/python3.5/site-packages/perceval/backends/mozilla/crates.py", line 33, in <module>
    from ...backend import (Backend,
ImportError: cannot import name 'metadata'
```

This also affectes GrimoireELK and Mordred when importing crates.

**Comment by sduenas** [comment]
This package doesn't work with the latest version of Perceval. We need to update it. The same problem can be found in `perceval-opnfv` and in `perceval-puppet`.

**Comment by jgbarah** [comment]
I see. If you don't mind, let's leave this open until we can have working versions of Perceval* again.

**Comment by sduenas** [comment]
The current version works with the latest one of Perceval. Closing this issue.
