### ISSUE TITLE
Please do not crawl crates.io/api/v1/crates

### ISSUE THREAD

**Issue by sgrif** [chaoss/grimoirelab-perceval-mozilla#37]
This API endpiont includes some information that is non-trivial to generate, like recent downloads. It is meant to be consumed by humans (such as when visiting our web UI). The data you're collecting can more easily be obtained by pulling down the index from https://github.com/rust-lang/crates.io-index

/cc @ashleygwilliams

**Comment by hmitsch** [comment]
Hi @sgrif and @ashleygwilliams, 

thanks for finding us and opening this issue. This API crawl was built by Mozilla's Open Innovation team. I take ownership of moving forward towards a sustainable solution in https://github.com/mozilla/participation-metrics-org/issues/169

I hope this is not causing too many issues at the moment? Do you want us to stop crawling for the time being?

Best regards,
   Henrik

**Comment by ashleygwilliams** [comment]
hi @hmitsch ! could you speak a bit more about the goals that the open innovation team has in crawling us? since we are working with you, i imagine we can get you the data in a more efficient way than what you are currently doing.

**Comment by ashleygwilliams** [comment]
@hmitsch i'd love to sit down with ya'll and figure out how we can get you the data in a less resource intensive way. can we schedule a meeting?

**Comment by valeriocos** [comment]
Some Perceval backends for the Mozilla ecosystem are available at https://github.com/chaoss/grimoirelab-perceval-mozilla.  You can find the backend for _crates.io_ at: https://github.com/chaoss/grimoirelab-perceval-mozilla/blob/master/perceval/backends/mozilla/crates.py

**Comment by jgbarah** [comment]
Hi, Henrik,

The code is here:

https://github.com/chaoss/grimoirelab-perceval-mozilla/blob/master/perceval/backends/mozilla/crates.py

All backends specific to Mozilla are in perceval-mozilla

Saludos,

	Jesus

On Tue, 2018-04-17 at 21:22 +0000, Henrik Mitsch wrote:
> @sanacl @dicortazar can you help me find the source code for the
> crates.io connector. I was looking for it in the perceval repo and
> couldn't find it: https://github.com/chaoss/grimoirelab-perceval/tree
> /master/perceval/backends/core
> -Henrik
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Bitergia: http://bitergia.com
/me at Twitter: https://twitter.com/jgbarah

**Comment by hmitsch** [comment]
Thank you so much for the quick answer!

**Comment by hmitsch** [comment]
@ashleygwilliams can you tell us if you currently block our user agent from crawling crates.io? If yes, can we unblock it until we agree on a new path forward?

-Henrik

**Comment by sgrif** [comment]
The crawler is currently being blocked. It was crawling at a rate that caused unreasonable load on our servers, and impacted the response times for other users.
