### ISSUE TITLE
Incorrect number of posted questions in Kitsune

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-perceval-mozilla#79]
I found discrepancies in the data Bitergia Analytics provides using GrimoireLab for the Thunderbird support forum (it uses a Kitsune backend).

According to the original data source, there are 392 questions asked from Oct 21 to Oct 27, both included. Both in 2024. This can be calculated following these steps:
 - go to https://stats.thunderbird.net/#support
 - count the questions from Oct 21 to Oct 27, both included

I obtained the number of questions for Kitsune in the thunderbird.biterg.io instance (publicly available) and the numbers do not match. I tried querying directly the raw indexes and the error is still there. The number of questions for the same period above mentioned is 260

It seems the error is in Perceval, but because I'm not sure I prefer to put the report here.

**Comment by sduenas** [comment]
I found a bug on the kitsune backend and it's related to how resuming works.

When an offset is given, the backend considers it as the number of questions that will discard before getting new data. For example, if the first time that questions were retrieved, there were 10 questions the offset will be 10. If we run again the backend using 10 as offset, it will discard the 10 first questions and retrieve questions from there. This 10 first questions could have been updated in between the two runs, so the new updates won't be retrieved.
